### PR TITLE
add privacy policy pdf

### PR DESCRIPTION
**Pull request by silviopaganini**
need to yarn install and

react-native link react-native-fetch-blob
react-native link react-native-pdf

closes #109

### CODE REVIEW

**Comment by ianmcgregor** [comment]
This one is failing. Just going to open the PDF in Safari for now - do you think apple will have an issue with that?

**Comment by silviopaganini** [comment]
hmmm i dont think so, would be good to have it, let me check why it's failing...

**Comment by silviopaganini** [comment]
just needed to mock the function, let's see if that works

**Comment by silviopaganini** [comment]
fixed tests

**Pull request closed without merging**
